config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "shops#index"
  resources :shops do
    resources :reviews, only: :create
  end
  get 'shops/search'
  namespace :admin do
    resources :restaurants do
      collection do
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '和食' },
    { id: 3, name: '洋食' },
    { id: 4, name: 'フランス料理' },
    { id: 5, name: 'スペイン料理' },
    { id: 6, name: 'イタリア料理' },
    { id: 7, name: '中華料理' },
    { id: 8, name: 'タイ料理' },
    { id: 9, name: '韓国料理' },
    { id: 10, name: 'ベトナム料理' },
    { id: 11, name: 'インド料理' },
    { id: 12, name: 'カフェ' }
  ]

  include ActiveHash::Associations
  has_many :shops
  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '--' },
    {id: 2, name: '北海道'},
    {id: 3, name: '青森県'},
    {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'},
    {id: 6, name: '秋田県'},
    {id: 7, name: '山形県'},
    {id: 8, name: '福島県'},
    {id: 9, name: '茨城県'},
    {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'},
    {id: 12, name: '埼玉県'},
    {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'},
    {id: 15, name: '神奈川県'},
    {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'},
    {id: 18, name: '石川県'},
    {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'},
    {id: 21, name: '長野県'},
    {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'},
    {id: 24, name: '愛知県'},
    {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'},
    {id: 27, name: '京都府'},
    {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'},
    {id: 30, name: '奈良県'},
    {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'},
    {id: 33, name: '島根県'},
    {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'},
    {id: 36, name: '山口県'},
    {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'},
    {id: 39, name: '愛媛県'},
    {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'},
    {id: 42, name: '佐賀県'},
    {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'},
    {id: 45, name: '大分県'},
    {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'},
    {id: 48, name: '沖縄県'}
  ]
  include ActiveHash::Associations
  has_many :shops
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  belongs_to :user

  validates :text , presence: true, length: { maximum: 100 }
end

app/models/shop.rb
class Shop < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :prefecture

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :shop_tag_relations, dependent: :destroy
  has_many :tags, through: :shop_tag_relations
  has_one_attached :image

    with_options presence: true do
      validates :image
      validates :shop_name , length: { maximum: 40 }
      validates :profile,    length: { maximum: 400 }
      validates :p_num,      format: { with: /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/},
                             length: { in: 1..12 }  
      validates :p_code,     format: { with: /\A\d{3}[-]\d{4}\z/}
      validates :city
      validates :address
        with_options numericality: { other_than: 1 } do
          validates :genre_id
          validates :prefecture_id
        end
    end
end

app/models/shop_tag_relation.rb
class ShopTagRelation < ApplicationRecord
  belongs_to :shop
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :shop_tag_relations, dependent: :destroy
  has_many :shops, through: :shop_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops
  has_many :reviews
  with_options presence: true do
    validates :name
    validates :email, uniqueness: true
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/, message: 'Include both letters and numbers'}
    with_options format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'Full-width characters'} do
     validates :l_name 
     validates :f_name
    end
    with_options format: { with: /\A[ァ-ヶー－]+\z/, message: 'Full-width katakana characters'} do
     validates :l_name_r
     validates :f_name_r
    end
    validates :birthday
    validates :p_num, format: { with: /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/},
                      length: { in: 1..13 }
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :if_not_admin
  def index
    
  end

  def new
    @shop= Shop.new
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.valid?
      @shop.save
      redirect_to admin_restaurants_path
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
  end

  private
  def if_not_admin
    unless current_user.admin?
    redirect_to root_path 
    end
  end
  def shop_params
    params.require(:shop).permit(:image, :shop_name, :genre_id, :profile, :p_num, :p_code, :prefecture_id, :city, :address, :building, tag_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :l_name, :f_name, :l_name_r, :f_name_r, :birthday, :p_num, :owner])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @reviews = Review.create(review_params)
    redirect_to shop_path (params[:shop_id])
  end

  private
  def review_params
    params.require(:review).permit(:text).merge(user_id: current_user.id, shop_id: params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :search_shop, only: [:index, :search]
  before_action :set_shop, only:[:show]
  def index
    @shops = Shop.all.order("created_at DESC")
    set_shop_column
    set_tag_column
  end

  def show
    @review = Review.new
    @reviews = @shop.reviews.includes(:user)
  end

  def search
    @results = @p.result.includes(:shop)
  end

  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def search_shop
    @p = Shop.ransack(params[:q])
  end

  def set_shop_column
    @shop_genre = Shop.select("genre").distinct
    @shop_address = Shop.select("prefecture_id").distinct
  end

  def set_tag_column
    @tag_name = Tag.select("id").distinct
  end
  
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      店舗情報入力
    </h1>
  </div>

  <%= render 'devise/shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class="img-upload">
        <div class="form-text">
          店舗画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, id:"item-image" %>
        </div>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :shop_name, class:"input-default", id:"shop-name", placeholder:"40字以内", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      ジャンル
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"shop-genre"}) %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">タグ</label>
      <span class="indispensable">必須</span>
    </div>
    <div class="col-md-4 checkbox-list">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name ) %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店舗プロフィール</label>
      <span class="indispensable">必須</span>
    </div>
      <div class='input-profile-wrap'>
        <%= f.text_area :profile, class:"input-default profile", id:"profile", placeholder:"400字以内", maxlength:"400"%>
      </div>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_num, class:"input-default", id:"p_num", placeholder:"例)080-1234-5678" %>
  </div>

  <div><h1 class="input-headline">
      所在地入力
    </h1></div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">郵便番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_code, class:"input-default", id:"postal-code", placeholder:"例)123-4567", maxlength:"8" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      都道府県
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"shop--preficture"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">市町村</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :city, class:"input-default", id:"shop-city", placeholder:"市町村を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">番地</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :address, class:"input-default", id:"shop-address", placeholder:"番地を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">建物名</label>
    </div>
    <%= f.text_field :building, class:"input-default", id:"shop-building", placeholder:"建物名を入力" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "店舗を登録する" ,class:"add-shop-btn" %>
  </div>
</div>

app/views/admin/restaurants/destroy.html.erb
<%= render partial: "devise/shared/header"%>
<div class="main update">
  <div class="complete">
      <h3>削除が完了しました。</h3>
      <div class="update-button">
        <%= link_to 'トップページに戻る', root_path, class: "admin-button" %>
      </div>
  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "devise/shared/header"%>

<%= form_with model: @shop, url: admin_restaurant_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      店舗情報入力
    </h1>
  </div>

  <%= render 'devise/shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class="img-upload">
        <div class="form-text">
          店舗画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, id:"item-image" %>
        </div>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :shop_name, class:"input-default", id:"shop-name", placeholder:"40字以内", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      ジャンル
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"shop-genre"}) %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">タグ</label>
      <span class="indispensable">必須</span>
    </div>
    <div class="col-md-4 checkbox-list">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name ) %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店舗プロフィール</label>
      <span class="indispensable">必須</span>
    </div>
      <div class='input-profile-wrap'>
        <%= f.text_area :profile, class:"input-default profile", id:"profile", placeholder:"400字以内", maxlength:"400"%>
      </div>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_num, class:"input-default", id:"p_num", placeholder:"例)080-1234-5678" %>
  </div>

  <div><h1 class="input-headline">
      所在地入力
    </h1></div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">郵便番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_code, class:"input-default", id:"postal-code", placeholder:"例)123-4567", maxlength:"8" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      都道府県
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"shop--preficture"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">市町村</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :city, class:"input-default", id:"shop-city", placeholder:"市町村を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">番地</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :address, class:"input-default", id:"shop-address", placeholder:"番地を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">建物名</label>
    </div>
    <%= f.text_field :building, class:"input-default", id:"shop-building", placeholder:"建物名を入力" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "店舗を登録する" ,class:"add-shop-btn" %>
  </div>
</div>
<% end %>

app/views/admin/restaurants/index.html.erb
<%= render "devise/shared/admin-header"%>

<div class="adimin-main">
  
  <div class="menu-main">
    <div class="menu-list">
      <div class="menu"><%= link_to 'ショップ情報を追加', new_admin_restaurant_path, class: "add-shop button" %></div>
      <div class="menu"><%= link_to 'ユーザー情報を管理', new_admin_restaurant_path, class: "admin-user button" %></div>
    </div>
  </div>
  
</div>

app/views/admin/restaurants/new.html.erb
<%#= render "devise/shared/second-header"%>

<%= form_with model: @shop, url: admin_restaurants_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      店舗情報入力
    </h1>
  </div>

  <%= render 'devise/shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class="img-upload">
        <div class="form-text">
          店舗画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, id:"item-image" %>
        </div>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :shop_name, class:"input-default", id:"shop-name", placeholder:"40字以内", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      ジャンル
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"shop-genre"}) %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">タグ</label>
      <span class="indispensable">必須</span>
    </div>
    <div class="col-md-4 checkbox-list">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name ) %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">店舗プロフィール</label>
      <span class="indispensable">必須</span>
    </div>
      <div class='input-profile-wrap'>
        <%= f.text_area :profile, class:"input-default profile", id:"profile", placeholder:"400字以内", maxlength:"400"%>
      </div>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_num, class:"input-default", id:"p_num", placeholder:"例)080-1234-5678" %>
  </div>

  <div><h1 class="input-headline">
      所在地入力
    </h1></div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">郵便番号</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :p_code, class:"input-default", id:"postal-code", placeholder:"例)123-4567", maxlength:"8" %>
  </div>
  <div class="form-group">
    <div class="form-text">
      都道府県
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"shop--preficture"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">市町村</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :city, class:"input-default", id:"shop-city", placeholder:"市町村を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">番地</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :address, class:"input-default", id:"shop-address", placeholder:"番地を入力" %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">建物名</label>
    </div>
    <%= f.text_field :building, class:"input-default", id:"shop-building", placeholder:"建物名を入力" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "店舗を登録する" ,class:"add-shop-btn" %>
  </div>
</div>
<% end %>

<%#= render "devise/shared/second-footer"%>

app/views/admin/restaurants/update.html.erb
<%= render partial: "devise/shared/header"%>
<div class="main update">
  <div class="complete">
      <h3>編集が完了しました。</h3>
      <div class="update-button">
        <%= link_to '店舗詳細ページに戻る', shop_path(@shop), class: "admin-button" %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rest32531</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/index.html.erb
<%= render partial: "devise/shared/header"%>

<div class="main">
  <div class="left-area">
    <div class="form-title">検索フォーム</div>

    <div class="search-form">
      <%= search_form_for @p, url: shops_search_path do |f| %>
        <div class="form form-genre">
          <div class="form-title">ジャンル</div>
          <%= f.label :genre_eq, 'ジャンル' %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name,  include_blank: '指定なし' %>
          <br>
        </div>

        <div class="form form-address">
          <div class="form-title">所在地</div>
          <%= f.label :prefecture_eq, '所在地' %>
          <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name,  include_blank: '指定なし' %>
          <br>
        </div>

        <div class="form-tag">
          <%= f.label :tag_eq, 'こだわり条件' %>
          <%= f.collection_radio_buttons :id, Tag.all, :id, :name %>
          <br>
        </div>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="right-area">
    <div class="shop">
      <div class="title">レストラン一覧</div>
    </div>
    <div class="search-value"></div>
    <div class="shop-group">
      <div class="shop-list">
        <% @shops.each do |shop| %>
        <div class="shop-detail-group">
          <div class="shop-image">
            <%= image_tag shop.image , class: 'shop-image'%>
          </div>

          <div class="shop-reserve-group">

              <div class="title-address-genre">
                <div class="index-title"><%= shop.shop_name %></div>
                <div class="index-genre"><%= shop.genre.name %></div>
                <div class="index-address"><%= shop.prefecture.name %></div>
              </div>

            <div class="shop-tags">
              <ul class="tag">
                  <% shop.tags.each do |tag| %>
                  <li class="tag-list">
                    <%=tag.name%>
                  </li>
                  <%end%>
              </ul>
            </div>

              <div class="shop-show-button">
              <%= link_to '店舗詳細確認・予約', shop_path(shop), class: "shop-show" %>
              </div>
          </div>
        </div>
       <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: "devise/shared/footer"%>

app/views/shops/show.html.erb
<%= render partial: "devise/shared/header" %>
<div class="main-show">
  <div class="shop-header">
    <div class="shop-title-show">
      <%= @shop.shop_name %>
    </div>
    <div class="shop-genre-tags">
      <div class="shop-genre-show">
        <%= @shop.genre.name %>
      </div>
      <div class="shop-tags-show">
      <ul class="tags-show">
          <% @shop.tags.each do |tag| %>
          <li class="tag-list">
            <%=tag.name%>
          </li>
          <%end%>
      </ul>
      </div>
    </div>
  </div>

  <div class="contents-show">
    <div class="area-show">
      <div class="shop-image-box-show">
        <%= image_tag @shop.image , class: 'shop-image-show'%>
      </div>

      <div class="group-show">
        <div class="shop-profile-title">
          <h1>ショッププロフィール</h1>
        </div>

        <div class="shop-profile-show">
          <%= @shop.profile %>
        </div>
      </div>

      <div class="detail-show">
        <div class="shop-profile-title">
          <h1>店舗基本情報</h1>
        </div>
        <div class="shop-info-box show">
          <div class="shop-box pnum">
            <div class="shop-info-title show">
              <h2>予約・お問い合わせ</h2>
            </div>
            <div class="info p-num"><%= @shop.p_num %></div>
          </div>
        </div>

        <div class="shop-info-box show">
          <div class="shop-box pnum">
            <div class="shop-info-title show">
              <h2>所在地</h2>
            </div>
            <div class="p-code-address">
              <div class="info p-code">〒<%= @shop.p_code %></div>
              <div class="info address"><%= @shop.prefecture.name + @shop.city + @shop.address + @shop.building %></div>
            </div>
          </div>
        </div>
        
        <div class="shop-review-box show">
          <div class="shop-profile-title">
            <h2>口コミ</h2>
          </div>
          <div class="review-box reviews">
            <% @reviews.each do |review| %>
              <div class="review-text"><%= review.text %></div>
              <div class="review-user-time">
                <%= "#{review.user.name}  #{l review.created_at}" %>
              </div>
            <% end %>
          </div>
        </div>
           <div class="review-form">
            <% if user_signed_in? %>
              <%= form_with(model: [@shop, @review], local: true) do |form| %>
                <%= form.text_area :text, placeholder: "100字以内", class:"review-text", rows: "2" %>
                <%= form.submit "レビューを投稿する", class: "review-form-button" %>
              <% end %>
            <% else %>
              <div class="review-form">口コミの投稿には新規登録/ログインが必要です</div>
            <% end %>
            </div>
        

      <div class="shop-info-box show">
        <% if user_signed_in? && current_user.admin? %>
          <div class="admin show">
            <div><%= link_to '戻る', root_path, class: "admin-button" %></div>
            <div><%= link_to '編集', edit_admin_restaurant_path, class: "admin-button" %></div>
            <div><%= link_to '削除', admin_restaurant_path(@shop.id), method: :delete, class: "admin-button" %></div>
          </div>
        <% elsif user_signed_in? %>
          <div class="admin show">
            <div><%= link_to '戻る', root_path, class: "admin-button" %></div>
            <div><%= link_to 'ネット予約', root_path, class: "admin-button" %></div>
          </div>
        <% else %>
        <% end %>
      </div>
    </div>
  </div>
</div>